CREATE TABLE artist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    details TEXT,
    country TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE album (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cover_image_ref TEXT,
    artist_id BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fkmwc4fyyxb6tfi0qba26gcf8s1
        FOREIGN KEY (artist_id)
        REFERENCES artist(id)
);

CREATE TABLE song (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    audio_ref TEXT NOT NULL,
    album_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fkrcjmk41yqj3pl3iyii40niab0
        FOREIGN KEY (album_id)
        REFERENCES album(id)
);

CREATE TABLE song_artist (
    song_id BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,

    CONSTRAINT pk_song_artist
        PRIMARY KEY (song_id, artist_id),

    CONSTRAINT fka29cre1dfpdj3gek88ukv43cc
        FOREIGN KEY (song_id)
        REFERENCES song(id),

    CONSTRAINT fk9tevojs24wnwin3di24wlao1m
        FOREIGN KEY (artist_id)
        REFERENCES artist(id)
);