-- ============================================================
-- V3: Add genre table and song.genre_id foreign key
-- ============================================================

CREATE TABLE genre (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_genre_name UNIQUE (name)
);

-- Seed data: common genres so we have something to attach to songs.
INSERT INTO genre (name, description, created_at, updated_at) VALUES
    ('Bollywood',  'Indian film music',        NOW(), NOW()),
    ('Pop',        'Popular music',            NOW(), NOW()),
    ('Rock',       'Rock music',               NOW(), NOW()),
    ('Hip Hop',    'Hip hop and rap',          NOW(), NOW()),
    ('Classical',  'Indian classical music',   NOW(), NOW());

-- Add nullable FK to song
ALTER TABLE song
    ADD COLUMN genre_id BIGINT,
    ADD CONSTRAINT fk_song_genre
        FOREIGN KEY (genre_id) REFERENCES genre(id)
        ON DELETE RESTRICT;

-- Index for lookups by genre (Postgres does not auto-index FK columns)
CREATE INDEX idx_song_genre_id ON song(genre_id);